computan.timesheet/Controllers/ContactCompaniesController.cs
using computan.timesheet.Contexts;
using computan.timesheet.core;
using computan.timesheet.Helpers;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace computan.timesheet.Controllers
{
    [CustomeAuthorizeAttribute]
    public class ContactCompaniesController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: ContactCompanies
        public ActionResult Index()
        {
            return View(db.ContactCompany.ToList());
        }

        // GET: ContactCompanies/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ContactCompany contactCompany = db.ContactCompany.Find(id);
            if (contactCompany == null)
            {
                return HttpNotFound();
            }

            return View(contactCompany);
        }

        // GET: ContactCompanies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContactCompanies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,clientid")] ContactCompany contactCompany)
        {
            if (ModelState.IsValid)
            {
                ContactCompany objcompany = db.ContactCompany.Where(x => x.name == contactCompany.name).FirstOrDefault();
                if (objcompany != null)
                {
                    ModelState.AddModelError("name", "Sorry, Contact domain already exist.");
                    return View(contactCompany);
                }

                db.ContactCompany.Add(contactCompany);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contactCompany);
        }

        // GET: ContactCompanies/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ContactCompany contactCompany = db.ContactCompany.Find(id);
            if (contactCompany == null)
            {
                return HttpNotFound();
            }

            return View(contactCompany);
        }

        // POST: ContactCompanies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,clientid")] ContactCompany contactCompany)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contactCompany).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contactCompany);
        }

        // GET: ContactCompanies/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ContactCompany contactCompany = db.ContactCompany.Find(id);
            if (contactCompany == null)
            {
                return HttpNotFound();
            }

            return View(contactCompany);
        }

        // POST: ContactCompanies/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ContactCompany contactCompany = db.ContactCompany.Find(id);
            db.ContactCompany.Remove(contactCompany);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

computan.timesheet/Views/ContactCompanies/Create.cshtml
@model computan.timesheet.core.ContactCompany
@{ ViewBag.Title = "Add Contact Company"; }

@section header {
    <div style="background-color: #fff;" class="panel page-header border-top-primary">
        <div class="page-header-content">
            <div class="page-title">
                <h5>
                    <i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Timesheet</span> - Manage Contact Domains
                    <small class="display-block">Manage Contact Domain</small>
                </h5>
            </div>
            <div class="heading-elements">
                <div class="btn-group">
                    <a href="/ContactCompanies/create" class="btn btn-primary"><i class="icon-list3 position-left"></i>Add New Company</a>
                </div>
            </div>
            <a class="heading-elements-toggle">
                <i class="icon-menu"></i>
            </a>
        </div>
        <div style="border-bottom: 0; box-shadow: none; margin-bottom: 0;" class="breadcrumb-line">
            <ul class="breadcrumb">
                <li>
                    <a href="/Home/index"><i class="icon-home2 position-left"></i>Home</a>
                </li>
                <li>
                    <a href="/ContactCompanies/index">Companies</a>
                </li>
            </ul>
        </div>
    </div>
}

<div class="panel panel-default">
    <div class="panel-body">
        <div class="tabbable">
            <ul class="nav nav-tabs nav-tabs-highlight">
                <li class=""> @Html.ActionLink("Contacts", "Index", "Contacts") </li>
                <li class="active"> @Html.ActionLink("Companies", "Index", "ContactCompanies") </li>
            </ul>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                    <div class="form-group">
                        <div class="col-md-12">
                            <label class="control-label" for="name">Company Name</label>
                            @Html.EditorFor(model => model.name, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.name, "", new {@class = "text-danger"})
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 text-center">
                            <input type="submit" value="Create" class="btn btn-primary"/>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

computan.timesheet/Views/ContactCompanies/Delete.cshtml
@model computan.timesheet.core.ContactCompany
@{ ViewBag.Title = "Delete"; }
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ContactCompany</h4> <hr/>
    <dl class="dl-horizontal">
        <dt> @Html.DisplayNameFor(model => model.name) </dt>
        <dd> @Html.DisplayFor(model => model.name) </dd>
        <dt> @Html.DisplayNameFor(model => model.clientid) </dt>
        <dd> @Html.DisplayFor(model => model.clientid) </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

computan.timesheet/Views/ContactCompanies/Details.cshtml
@model computan.timesheet.core.ContactCompany
@{ ViewBag.Title = "Details"; }
<h2>Details</h2>
<div>
    <h4>ContactCompany</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt> @Html.DisplayNameFor(model => model.name) </dt>
        <dd> @Html.DisplayFor(model => model.name) </dd>
        <dt> @Html.DisplayNameFor(model => model.clientid) </dt>
        <dd> @Html.DisplayFor(model => model.clientid) </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {Model.id}) |
    @Html.ActionLink("Back to List", "Index")
</p>

computan.timesheet/Views/ContactCompanies/Edit.cshtml
@model computan.timesheet.core.ContactCompany
@{ ViewBag.Title = "Contact Domain"; }

@section header {
    <div style="background-color: #fff;" class="panel page-header border-top-primary">
        <div class="page-header-content">
            <div class="page-title">
                <h5>
                    <i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Timesheet</span> - Manage Contact Domains
                    <small class="display-block">Manage Contact Domain</small>
                </h5>
            </div>
            <div class="heading-elements">
                <div class="btn-group">
                    <a href="/ContactCompanies/create" class="btn btn-primary"><i class="icon-list3 position-left"></i>Add New Company</a>
                </div>
            </div>
            <a class="heading-elements-toggle">
                <i class="icon-menu"></i>
            </a>
        </div>
        <div style="border-bottom: 0; box-shadow: none; margin-bottom: 0;" class="breadcrumb-line">
            <ul class="breadcrumb">
                <li>
                    <a href="/Home/index"><i class="icon-home2 position-left"></i>Home</a>
                </li>
                <li>
                    <a href="/ContactCompanies/index">Companies</a>
                </li>
            </ul>
        </div>
    </div>
}

<div class="panel panel-default">
    <div class="panel-body">
        <div class="tabbable">
            <ul class="nav nav-tabs nav-tabs-highlight">
                <li class=""> @Html.ActionLink("Contacts", "Index", "Contacts") </li>
                <li class="active"> @Html.ActionLink("Companies", "Index", "ContactCompanies") </li>
            </ul>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                    @Html.HiddenFor(model => model.id)
                    <div class="form-group">
                        <div class="col-md-12">
                            <label class="control-label" for="name">Company Name</label>
                            @Html.EditorFor(model => model.name, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.name, "", new {@class = "text-danger"})
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 text-center">
                            <input type="submit" value="Save" class="btn btn-primary"/>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

computan.timesheet/Views/ContactCompanies/Index.cshtml
@model IEnumerable<computan.timesheet.core.ContactCompany>
@{ ViewBag.Title = "List Contact Domain"; }

@section header {
    <div style="background-color: #fff;" class="panel page-header border-top-primary">
        <div class="page-header-content">
            <div class="page-title">
                <h5>
                    <i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Timesheet</span> - Manage Contact Domains
                    <small class="display-block">Manage Contact Domain</small>
                </h5>
            </div>
            <div class="heading-elements">
                <div class="btn-group">
                    <a href="/ContactCompanies/create" class="btn btn-primary"><i class="icon-list3 position-left"></i>Add New Contact Domain</a>
                </div>
            </div>
            <a class="heading-elements-toggle">
                <i class="icon-menu"></i>
            </a>
        </div>
        <div style="border-bottom: 0; box-shadow: none; margin-bottom: 0;" class="breadcrumb-line">
            <ul class="breadcrumb">
                <li>
                    <a href="/Home/index"><i class="icon-home2 position-left"></i>Home</a>
                </li>
                <li>
                    <a href="/ContactCompanies/index">Companies</a>
                </li>
            </ul>
        </div>
    </div>
}

<div class="panel panel-default">
    <div class="panel-body">
        <div class="tabbable">
            <ul class="nav nav-tabs nav-tabs-highlight">
                <li class=""> @Html.ActionLink("Contacts", "Index", "Contacts") </li>
                <li class="active"> @Html.ActionLink("Companies", "Index", "ContactCompanies") </li>
            </ul>
            <div class="tab-content">
                <table class="table datatable-button-html5-basic" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                    <thead>
                    <tr role="row">
                        <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="First Name: activate to sort column descending"> @Html.DisplayNameFor(model => model.name) </th>
                        <th> @Html.DisplayName("Total Contacts Count") </th>
                        <th> @Html.DisplayName("Contacts") </th>
                        <th> </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td> @Html.DisplayFor(modelItem => item.name) </td>
                            <td> @item.ContactCollection.Count() </td>
                            <td> @Html.ActionLink("Load Contacts for domain", "Index", "Contacts", new {item.id}, new {@class = "btn btn-primary btn-xs"}) </td>
                            <td> @Html.ActionLink("Edit", "Edit", new {item.id}, new {@class = "btn btn-primary btn-xs"}) </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>